Feature/3 eonet api library
WildCodeSchool/remotefr-js-0920-p2-earth-events pull request #1
Opened 2020-10-29 14:52 UTC by e-floran

Functions are created in separated files. Please check if everything runs smoothly.
Explanation comments can be found on top of each file, but if you want to know more about the format of the input for each function, please go to https://eonet.sci.gsfc.nasa.gov/docs/v3

2020-10-29 18:05 UTC, clovfr requested changes
L'idée derrière une *library*, est de permettre de limiter la redondance de code tout en ayant qu'un seul module à importer.

Malheureusement, ici je vois 4× le même script, à une ou deux variations près (principalement le *endpoint* qui change) et pas de possibilité de récupérer un ID en particulier.

Essaie de reprendre tes scripts pour n'en faire qu'un seul. Par exemple :

```js
const defaultOptions = {/* … */}

function finder(endpoint, params) {/* qui lance une requête avec `params` pour filtres */}

function getter(endpoint, id) {/* qui récupère directement un objet via son `id` */}

const events = {
  find: (params) => finder('events', params),
  get: (id) => getter('events', id),
};
const categories = {
  find: (params) => finder('categories', params),
  get: (id) => getter('categories', id),
};
const geojson = {
  find: (params) => finder('geojson', params),
  get: (id) => getter('geojson', id),
};
const layers = {
  find: (params) => finder('layers', params),
  get: (id) => getter('layers', id),
};

export { events, categories, geojson, layers };
```

2020-10-29 18:05 UTC, ghost commented on src/App.jsx
> +      <EventsTest />
Le component `EventsTest` n'existe pas et de toute manière il n'est pas très utile d'avoir un component de test sur le projet (garde ça dans ta branche locale éventuellement, il faudra voir avec @bhubr la question des test unitaires).

Aussi, il vaudrait mieux annuler toutes les modifications de ce fichier pour éviter les conflits avec l'User Story 1.

2020-10-29 18:05 UTC, ghost commented on src/lib/Layers.js
> +  //   }
Un petit clean des commentaires ? ^^

2020-10-29 18:05 UTC, ghost commented on src/lib/EventsFinder.js
> +    params: { status: 'open' },
Pourquoi forcer `status: 'open'` par défaut ? 
Si je veux avoir tous les résultats, je serais obligé de passer `status: undefined` à la fonction.

2020-10-29 18:05 UTC, ghost commented on src/lib/EventsFinder.js
> +  }
Tu te compliques la tâche : pourquoi passer un objet `params` via un objet anonyme quand tu peux directement passer `params` à la fonction ?

```js
eventsFinder({params: {/* … */}});

// Versus

eventsFinder({/* … */});
```

Ainsi, tout ce bloc pourrait être optimisé : 
En plaçant `defaultOptions` à l'extérieur de la fonction `eventsFinder` et ensuite en clonant le premier et ne modifiant que la valeur de `options.params`:
```js
function eventsFinder(params = {}) {
  // éventuellement contrôler que `params` est bien un objet ici
  const options = { ...defaultOptions, params };
  /* … */
```

2020-10-29 18:05 UTC, clovfr commented on src/lib/Categories.js
> +    url: `https://eonet.sci.gsfc.nasa.gov/api/v3/categories/${input[0]}`,
Pas très RESTfull : `input[0]` est passé en id **avec** des paramètres de filtrages `input[1].params` ? 
Au pire le serveur va renvoyer une erreur, au mieux il va ignorer les `params`.

2020-10-29 18:05 UTC, clovfr commented on src/lib/EventsFinder.js
> +}
Attention au mix synchrone/asynchrone : 

`axios` retourne une `Promise`, ce qui veut dire que ta fonction `eventsFinder` va retourner `eventsList` *avant* qu'`axios` ai fini de traiter la requête API, et donc sera systématiquement une table vide. 
Pas nécessaire non plus de doubler la `axios` dans une autre fonction, tu peut directement mettre 
```js
return axios
  .request(obj)
  .then((response) => response.data.events)
```
et la Promise sera passée en sortie de la fonction `eventsFinder` qui sera à traiter de façon asynchrone (c'est à dire avec des `.then()`)

2020-10-29 18:56 UTC, e-floran commented on src/App.jsx
> +      <EventsTest />
C'était pour tester mon rendu. Je l'ai supprimé, mais j'ai oublié de nettoyer App.js en effet !

2020-10-29 19:30 UTC, clovfr commented on src/lib/Categories.js
> +    url: `https://eonet.sci.gsfc.nasa.gov/api/v3/categories/${input[0]}`,
Je viens de relire la doc de l'API et oui, il est possible de lister des events par cette méthode.
Mais du coup, il manque dans le script la possibilité de lister les catégories elles-même.

2020-10-29 22:08 UTC, e-floran commented on src/lib/EventsFinder.js
> +}
Je pense que c'est bon !

2020-10-29 23:20 UTC, e-floran commented
A priori, il ne reste plus que la problématique du ${input} dans l'URL pour layers et categories.
Dis moi si le reste est bon !

2020-10-29 23:22 UTC, clovfr commented
[Presque](https://www.wikihow-fun.com/Fusion-Dance-in-Dragonball-Z-(Video-Game)) :3

2020-10-29 23:48 UTC, clovfr commented
Actuellement, je peux faire :
```js
eventsFinder({
  field: 'events',  // required
  params: {
    days: 20,
    limit: 50
  },
})
  .then((data) => {/* … */})
```
mais pas :
```js
eventsFinder({
  field: 'events',  // required
  id: 'tempExtremes', // non-implanté
})
  .then((data) => {/* … */})
```

2020-10-30 07:59 UTC, e-floran commented
Parce que id ne fait pas partie des champs que l'on peut passer en paramètres :(

2020-10-30 08:01 UTC, bhubr requested changes, later dismissed
Change juste le return à la fin, pour le reste ça peut attendre.

2020-10-30 08:01 UTC, bhubr commented on src/lib/EventsFinder.js
> +
Tu pourrais créer une instance d'axios comme ceci (voir [creating an instance](https://github.com/axios/axios#creating-an-instance) dans la doc) :

```javascript
const instance = axios.create({
  baseURL: 'https://eonet.sci.gsfc.nasa.gov/api/v3',
});
```

Ensuite tu pourrais, dans tes appels, mettre uniquement les chemins relatifs. Par exemple :

```javascript
options.url = '/events';
```

Et pour envoyer ta requête : `instance.request(...)` au lieu de `axios.request(...)`

2020-10-30 08:01 UTC, bhubr commented on src/lib/EventsFinder.js
> +    if (input.params && input.params !== {}) {
attention, tu ne peux pas vérifier qu'un objet est non-vide en le comparant avec `{}` (`input.params !== {}` renverra toujours `false`).

Pour ça tu peux plutôt vérifier si l'objet a des clés : `Object.keys(input.params).length > 0`.

2020-10-30 08:01 UTC, bhubr commented on src/lib/EventsFinder.js
> +    }
Il y a une certaine redondance de ce bloc de code, mais c'est plutôt normal au début !

2020-10-30 08:01 UTC, bhubr commented on src/lib/EventsFinder.js
> +  return 'Something went wrong.';
Renvoie plutôt ceci : ```return Promise.resolve('Something went wrong (bad parameters)');```

2020-10-30 08:47 UTC, clovfr commented on src/lib/EventsFinder.js
> +
ou juste `axios.defaults.baseURL = 'https://eonet.sci.gsfc.nasa.gov/api/v3/';` sans créer d'instance.

2020-10-30 08:53 UTC, clovfr commented on src/lib/EventsFinder.js
> +  return 'Something went wrong.';
Avec `reject`plutôt…

```js
return Promise.reject(new Error('Something went wrong (bad parameters)'));
```

2020-10-30 09:00 UTC, e-floran commented on src/lib/EventsFinder.js
> +    }
Je veux bien en savoir plus à ce sujet !

2020-10-30 09:03 UTC, e-floran commented
Nouvelle version pushée !

2020-10-30 09:31 UTC, clovfr commented on src/lib/EventsFinder.js
>    };
[non bloquant] Passe directement le header dans la création d'instance, drop la method et utilises `instance.get` au lieu d'`instance.request`.

2020-10-30 09:35 UTC, e-floran commented on src/lib/EventsFinder.js
>    };
Comment est-ce que j'ajoute les params si je n'ai plus d'objet options ?

2020-10-30 09:35 UTC, clovfr requested changes
[non bloquant] Toujours pas de sélection par ID, elle sera nécessaire pour l'US7.

2020-10-30 09:35 UTC, clovfr commented on src/lib/EventsFinder.js
> +  return Promise.resolve('Something went wrong (bad parameters)');
Utilises `new Error()` dans `Promise.reject` et non `Promise.resolve`, sinon on ne peut pas `.catch()` l'erreur.

2020-10-30 09:37 UTC, e-floran commented
> [non bloquant] Toujours pas de sélection par ID, elle sera nécessaire pour l'US7.

Sauf erreur de ma part, l'ID ne fait pas partie des paramètres que l'on peut passer à l'API.

2020-10-30 09:38 UTC, e-floran commented on src/lib/EventsFinder.js
> +  return Promise.resolve('Something went wrong (bad parameters)');
Ah mince, j'ai copié ce que m'a conseillé Benoît. J'attends son avis pour ça du coup.

2020-10-30 09:39 UTC, clovfr commented on src/lib/EventsFinder.js
>    };
`const options = {}`

2020-10-30 09:45 UTC, clovfr commented
The RESTfull way : `https://eonet.sci.gsfc.nasa.gov/api/v3/events/<id>`.
[exemple](https://eonet.sci.gsfc.nasa.gov/api/v3/events/EONET_5137)

2020-10-30 10:31 UTC, clovfr requested changes
Il manque la gestion par ID pour `categories`.

2020-10-30 10:31 UTC, clovfr commented on src/lib/EventsFinder.js
> +      options.url = `/events/geojson/${input.id}`;
L'API GeoJSON est un petit peu tricky… 

Il est lié à `events`, donc `/events/${input.id}/geojson` permet de récupérérs les `Features` d'un `event`, tandis que `/events/geojson/${input.id}` renverra une erreur HTTP 404.

2020-10-30 10:34 UTC, e-floran commented
> Il manque la gestion par ID pour `categories`.

J'ai une erreur 500 quand je rajoute un ID sur categories :(

2020-10-30 10:41 UTC, bhubr commented on src/lib/EventsFinder.js
> +  return Promise.resolve('Something went wrong (bad parameters)');
Je me suis complètement planté (8h40 j'étais pas réveillé, faut croire).

Il faut effectivement utiliser `Promise.reject` mettre dedans `new Error('Something went wrong...')`

2020-10-30 10:44 UTC, e-floran commented on src/lib/EventsFinder.js
> +  return Promise.resolve('Something went wrong (bad parameters)');
C'est cette formulation là, donc : 
return Promise.reject(new Error('Something went wrong (bad parameters)'));

2020-10-30 10:56 UTC, clovfr commented on src/lib/EventsFinder.js
> +    }
Tu n'as besoin de le faire qu'une fois, juste après avoir déclaré `options` (ligne 13), puisqu'il n'est pas dépendant de la valeur de `input.field`.

2020-10-30 11:16 UTC, clovfr requested changes

2020-10-30 11:16 UTC, clovfr commented on src/lib/eonet.js
>      return instance.get(options).then((response) => response.data.events);
Retourne juste `response.data`, sinon ça pose problème avec les requêtes par ID.

2020-10-30 11:16 UTC, clovfr commented on src/lib/eonet.js
>      return instance.get(options).then((response) => response.data.features);
Retourne juste `response.data`, sinon ça pose problème avec les requêtes par ID.

2020-10-30 11:16 UTC, clovfr commented on src/lib/eonet.js
> -    }
Pourquoi ne pas garder `input.id` au lieu de `input.categorie` pour la cohérence ?

Je ne peux pas non plus lister les catégories.

2020-10-30 11:23 UTC, e-floran commented on src/lib/eonet.js
> -    }
- Parce que ce sont deux choses différentes, ça me semble plus clair comme ça.

Comment ça tu ne peux pas lister les categories ?

2020-10-30 14:13 UTC, clovfr commented on src/lib/eonet.js
> -    }
`input.categories` équivaut à `input.id` dans les autres requêtes. (REST : `/<type>`, `/<type>?<queryString>`, `/<type>/<id>`)

2020-10-30 14:16 UTC, clovfr commented on src/lib/eonet.js
> -    }
aussi, je peux faire 
```js
eonet({field, 'events'})`
```
mais pas 
```js
eonet({field, 'categories'})
```

2020-10-30 14:31 UTC, e-floran commented on src/lib/eonet.js
> -    }
Pourquoi est-ce que tu ne pourrais pas faire `eonet({field: 'categories'})` ?
field est juste utilisé par la fonction, ce n'est pas envoyé directement à l'API.

2020-10-30 14:58 UTC, clovfr commented
Bug avec les url relatives sur les instances d'axios : il faut passer `url` non pas dans l'objet `options` mais en premier paramètre de la fonction. Du coup, comme il ne te reste que `params` dans `options`, tu peux passer directement `params` dans le second paramètre d'`axios`.

Quick fix :
```js
return instance.get(options.url, options.params).then((response) => response.data);
```

cf: https://github.com/axios/axios/issues/478#issuecomment-253254385

2020-10-30 15:28 UTC, clovfr commented on src/lib/eonet.js
> -    }
Car ça renvoi ça call `https://eonet.sci.gsfc.nasa.gov/api/v3/categories/undefined` qui renvoi une erreur 500.

2020-11-01 13:18 UTC, e-floran commented on src/lib/eonet.js
> -    }
J'ai rajouté une condition pour vérifier qu'on a bien rentré une categorie ;)

2020-11-01 16:35 UTC, clovfr requested changes
Il y a un problème avec l'API : certaines requêtes sont retournées auformat JSON mais avec un en-tête `application/rss+xml`. Du coup, axios retourne `Erreur d’analyse XML : mal formé`.

Aussi il n'est pas possible de lister les `layers` (même travail à faire que pour `categories`) et je ne sais toujours pas pourquoi tu utilises `input.categories` au lieu de `input.id` comme pour `events`, `geojson` et [j'espère] `layers`.

Enfin, tu pourrais faire une seul `instance.get` à la fin du fichier (en vérifiant `options.url` par exemple, sinon `Promise.reject`).

2020-11-01 16:35 UTC, clovfr commented on src/lib/eonet.js
> +      options.url = `/categories/`;
Pas de slash à la fin de l'URL (renvoi une erreur CORS)

2020-11-02 10:13 UTC, e-floran commented
> Il y a un problème avec l'API : certaines requêtes sont retournées auformat JSON mais avec un en-tête `application/rss+xml`. Du coup, axios retourne `Erreur d’analyse XML : mal formé`.


J'avais raté ce message désolé : À quoi ça peut-être dû cet en-tête sur certaines requêtes mais pas toutes ?

2020-11-02 10:20 UTC, clovfr commented
~~À une API codé avec le cul ?~~
Dans les en-têtes HTTP, le serveur annonce un fichier au format XML alors que le contenu est structuré en JSON. Du coup axios essai de parser la réponse comme si elle était en XML, ce qui provoque une erreur.

2020-11-02 10:21 UTC, clovfr commented
Je pense qu'on peut avancer et laisser ce problème à plus tard.

2020-11-02 10:23 UTC, e-floran commented
Si il faut juste modifier cette ligne : `    headers: { 'Content-Type': 'application/json' },`
ça peut se faire !

2020-11-02 10:27 UTC, clovfr commented
A priori le serveur n'écoute pas quel format on demande.
On va faire avec pour le moment et avancer (ouvrir un ticket bug pour plus tard?).

2020-11-02 10:27 UTC, clovfr approved these changes

2020-11-02 10:40 UTC, merged