Feature/12 last events
WildCodeSchool/remotefr-js-0920-p2-earth-events pull request #15
Opened 2020-11-13 11:07 UTC by e-floran

Ajout de l'onglet "Last events" qui repertorie les évènements passés depuis la dernière visite de l'utilisateur.

2020-11-13 11:50 UTC, clovfr requested changes
L'implantation de redux dans le composant est bonne, mais la méthode pour détecter une précédente visite n'est pas bonne.

2020-11-13 11:50 UTC, clovfr commented on src/App.jsx
> +    setTimeout(function () {
eslint râle : utilises des fonctions flèches

2020-11-13 11:50 UTC, clovfr commented on src/App.jsx
> +      console.log(lastVisit);
Pense à cleaner avant de PR ;)

2020-11-13 11:50 UTC, clovfr commented on src/App.jsx
> +    console.log(window.localStorage.getItem('lastVisit'));
clean

2020-11-13 11:50 UTC, clovfr commented on src/App.jsx
> +  }, [storageCount]);
Le timeout fait rafraîchir `lastVisit` dans localStorage toutes les 15secondes, du coup la requête API sera toujours équivalente à `{start: now(), end: now()}`.

2020-11-13 12:15 UTC, clovfr commented on src/App.jsx
> +    window.localStorage.setItem('lastVisit', new Date().toISOString());
il manque un `else` en début de ligne (s'il n'y a pas de valeur, alors la set). Mais il faudrait passer cette nouvelle valeur dans `setLastVisit` aussi.

2020-11-14 13:52 UTC, e-floran commented on src/App.jsx
> +    setTimeout(function () {
Ah mince, il ne disait rien chez moi...

2020-11-14 13:56 UTC, clovfr commented on src/App.jsx
> +    setTimeout(function () {
Après application du patch (je ne sais pas si c'est lié) le paramètre pour choisir le linter/prettier a sauté dans OSS/VCS. Vérifie si c'est toujours bon chez toi.

2020-11-14 13:57 UTC, e-floran commented on src/App.jsx
> +    window.localStorage.setItem('lastVisit', new Date().toISOString());
J'ai rajouté le else mais pas le passage à setLastVisit, puisque le but est de savoir si l'utilisateur est déjà venu, justement. Dans le cas contraire, le state doit être vide !

2020-11-14 14:19 UTC, clovfr requested changes

2020-11-14 14:19 UTC, clovfr commented on src/App.jsx
> +  }, []);
J'ai maintenant une erreur quand je charge la page avec un localStorage vierge.
Vérifie la présence de l'entré dans localStorage en premier et si elle n'existe pas, créé-la. Ensuite charge-la tout simplement.

*in a nutshell* : 
```js
if (!window.localStorage.getItem('lastVisit')) {
  window.localStorage.setItem('lastVisit', new Date().toISOString());
}
setLastVisit(window.localStorage.getItem('lastVisit').slice(0, 10));
```

2020-11-14 14:23 UTC, clovfr commented on src/App.jsx
> +  }, []);
Par contre, dans le render
```JS
{lastVisit === '' && (
  <p className="error">This is your first visit, please come again.</p>
)}
```
ne s'exécutera jamais

2020-11-14 18:47 UTC, e-floran commented
C'est tout bon ?

2020-11-15 14:41 UTC, clovfr commented
LGTM

2020-11-15 14:43 UTC, clovfr approved these changes

2020-11-16 08:45 UTC, merged